/* ============================================================
   Exercise & Stretch Library
   Researched from reputable clinical sources (AAOS / OrthoInfo,
   Physiopedia, Cleveland Clinic, HSS, NHS PT handouts).
   Each item is a home-program exercise commonly assigned in
   PT / chiropractic practice.
   ------------------------------------------------------------
   This file populates window.EXERCISE_DATA, consumed by index.html.
   ============================================================ */

window.REGIONS = [
  { id: "cervical", label: "Cervical", sub: "Neck" },
  { id: "thoracic", label: "Thoracic", sub: "Mid / Upper Back" },
  { id: "lumbar",   label: "Lumbar",   sub: "Lower Back" },
  { id: "hip",      label: "Hip",      sub: "Hip & Pelvis" },
  { id: "shoulder", label: "Shoulder", sub: "Shoulder & Rotator Cuff" },
  { id: "elbow",    label: "Elbow",    sub: "Elbow & Forearm" },
  { id: "wrist",    label: "Wrist",    sub: "Wrist & Hand" },
  { id: "knee",     label: "Knee",     sub: "Knee & Thigh" }
];

window.EXERCISE_DATA = [
  /* ---------------- CERVICAL ---------------- */
  { name: "Chin Tuck (Cervical Retraction)", region: "cervical", type: "strengthening",
    instructions: ["Sit or stand tall with shoulders relaxed.", "Gently draw your chin straight back, making a 'double chin'.", "Keep your eyes level and do not tilt your head.", "Hold, then relax back to start."],
    dosage: "10 reps, hold 5 seconds", frequency: "2-3x per day",
    tips: "Move slowly and keep the motion gentle. Stop if you feel sharp pain or dizziness.", equipment: "none" },
  { name: "Upper Trapezius Stretch", region: "cervical", type: "stretch",
    instructions: ["Sit tall and hold the edge of your chair with one hand.", "Tilt your opposite ear toward your shoulder.", "Use your free hand to gently guide the head for a light stretch.", "Hold, then return to center."],
    dosage: "Hold 20-30 seconds, 3-4 reps each side", frequency: "1-2x per day",
    tips: "Keep shoulders down and relaxed; pull only to a gentle stretch, never to pain.", equipment: "none" },
  { name: "Levator Scapulae Stretch", region: "cervical", type: "stretch",
    instructions: ["Sit tall and turn your head about 45 degrees toward one side.", "Look down toward your armpit on that side.", "Place the same-side hand on the back of your head and apply gentle pressure.", "Hold, then slowly release."],
    dosage: "Hold 20-30 seconds, 3-4 reps each side", frequency: "1-2x per day",
    tips: "You should feel the stretch along the back of the neck. Keep the pressure light.", equipment: "none" },
  { name: "Scalene (Anterior Neck) Stretch", region: "cervical", type: "stretch",
    instructions: ["Sit tall and gently anchor one shoulder down.", "Tilt your head to the opposite side.", "Slowly rotate your chin upward toward the ceiling.", "Hold, then return to neutral."],
    dosage: "Hold 20-30 seconds, 3 reps each side", frequency: "1-2x per day",
    tips: "Move into the stretch slowly. Stop if you feel tingling into the arm.", equipment: "none" },
  { name: "Cervical Rotation (Active ROM)", region: "cervical", type: "mobility",
    instructions: ["Sit or stand with good upright posture.", "Slowly turn your head to look over one shoulder.", "Return to center, then turn to the other side.", "Keep the movement smooth and pain-free."],
    dosage: "10 reps each direction", frequency: "2-3x per day",
    tips: "Stay within a comfortable range. Avoid forcing the end of the motion.", equipment: "none" },
  { name: "Cervical Side Bend (Active ROM)", region: "cervical", type: "mobility",
    instructions: ["Sit tall with shoulders relaxed.", "Tip one ear toward the same-side shoulder.", "Return to center, then repeat to the other side.", "Keep your nose facing forward throughout."],
    dosage: "10 reps each side", frequency: "2-3x per day",
    tips: "Let the head move on its own; do not hike the shoulder up to meet it.", equipment: "none" },
  { name: "Deep Neck Flexor Hold (Supine)", region: "cervical", type: "strengthening",
    instructions: ["Lie on your back with knees bent.", "Gently nod the chin as if saying 'yes' (chin tuck).", "Lift the head only a half-inch off the floor.", "Hold, then lower slowly."],
    dosage: "10 reps, hold 5-10 seconds", frequency: "1-2x per day",
    tips: "Keep the nod gentle; do not lead with the chin or strain the front of the neck.", equipment: "none" },
  { name: "Isometric Neck Press", region: "cervical", type: "strengthening",
    instructions: ["Sit tall and place your palm against your forehead.", "Gently press your head into your hand without moving.", "Hold the steady contraction, then relax.", "Repeat with hand on each side and back of the head."],
    dosage: "5 reps per direction, hold 5 seconds", frequency: "1-2x per day",
    tips: "There should be no head movement. Use only light to moderate effort.", equipment: "none" },
  { name: "Suboccipital Release Nod", region: "cervical", type: "mobility",
    instructions: ["Sit tall with a slight chin tuck.", "Make a small 'yes' nodding motion at the base of the skull.", "Keep the rest of the neck still.", "Return slowly to neutral."],
    dosage: "10 reps, hold 3 seconds", frequency: "2-3x per day",
    tips: "Keep the motion tiny and controlled at the top of the neck only.", equipment: "none" },
  { name: "Shoulder Blade Squeeze (Scapular Retraction)", region: "cervical", type: "strengthening",
    instructions: ["Sit or stand with arms relaxed at your sides.", "Gently draw both shoulder blades back and down.", "Imagine pinching a pencil between them.", "Hold, then relax."],
    dosage: "10 reps, hold 5 seconds", frequency: "2-3x per day",
    tips: "Avoid shrugging the shoulders up toward the ears during the squeeze.", equipment: "none" },
  { name: "Prone Cervical Extension", region: "cervical", type: "strengthening",
    instructions: ["Lie face down with your forehead resting on a folded towel, arms at your sides.", "Gently tuck your chin, then lift your forehead a small distance off the towel.", "Keep your gaze toward the floor so the neck stays long.", "Hold, then lower slowly."],
    dosage: "8-10 reps, hold 3-5 seconds", frequency: "1x per day",
    tips: "Lift only a small amount and lead with a chin tuck, not by craning the head back. Stop if you feel dizziness or sharp pain.", equipment: "towel" },
  { name: "Chin Tuck with Band Resistance", region: "cervical", type: "strengthening",
    instructions: ["Anchor a light band in front of you at head height and place the loop around the back of your head.", "Sit tall facing the anchor with light tension on the band.", "Draw your chin straight back into a gentle tuck against the band's pull.", "Hold, then slowly return forward with control."],
    dosage: "10 reps, hold 5 seconds", frequency: "1x per day",
    tips: "Use only light tension and keep the motion straight back, not a nod. Stop if you feel sharp pain or dizziness.", equipment: "resistance band" },
  { name: "Cervical Flexion Stretch", region: "cervical", type: "stretch",
    instructions: ["Sit tall with shoulders relaxed.", "Gently drop your chin toward your chest.", "Rest your hands lightly on the back of your head for a gentle stretch.", "Hold, then slowly raise your head back to level."],
    dosage: "Hold 20-30 seconds, 3 reps", frequency: "1-2x per day",
    tips: "Let the weight of your hands provide the stretch; do not pull hard. Stop if you feel tingling into the arms.", equipment: "none" },

  /* ---------------- THORACIC ---------------- */
  { name: "Thoracic Extension over Foam Roller", region: "thoracic", type: "mobility",
    instructions: ["Lie back with a foam roller across your upper back.", "Support your head with hands behind it.", "Gently arch your upper back over the roller and exhale.", "Roll to a new spot and repeat."],
    dosage: "5-8 gentle extensions per segment", frequency: "1-2x per day",
    tips: "Support the head so the neck does not fall back; keep abs lightly engaged.", equipment: "foam roller" },
  { name: "Cat-Cow", region: "thoracic", type: "mobility",
    instructions: ["Start on hands and knees with a flat back.", "Exhale and round the upper back toward the ceiling (cat).", "Inhale and gently arch, lifting the chest and tailbone (cow).", "Move slowly between the two positions."],
    dosage: "10 slow reps", frequency: "1-2x per day",
    tips: "Let the motion flow with your breath. Keep it pain-free and unforced.", equipment: "none" },
  { name: "Open Book Thoracic Rotation", region: "thoracic", type: "mobility",
    instructions: ["Lie on your side with knees bent and arms stretched out in front.", "Lift the top arm and rotate it open toward the floor behind you.", "Follow your hand with your eyes and let the chest open.", "Return slowly to start."],
    dosage: "8-10 reps each side", frequency: "1-2x per day",
    tips: "Keep the knees stacked and still so the motion comes from the upper back.", equipment: "none" },
  { name: "Seated Thoracic Rotation", region: "thoracic", type: "mobility",
    instructions: ["Sit tall with arms crossed over your chest.", "Slowly rotate your upper body to one side.", "Return to center, then rotate to the other side.", "Keep hips and pelvis facing forward."],
    dosage: "10 reps each side", frequency: "2-3x per day",
    tips: "Rotate from the mid-back, not the low back. Stay within a comfortable range.", equipment: "none" },
  { name: "Wall Angels", region: "thoracic", type: "mobility",
    instructions: ["Stand with back against a wall, knees slightly bent.", "Press your low back, upper back, and head to the wall.", "Raise arms into a goal-post and slide them up and down the wall.", "Keep elbows and wrists touching the wall as much as possible."],
    dosage: "10 reps", frequency: "1-2x per day",
    tips: "Keep the chin tucked and ribs down; only go as high as you can stay in contact.", equipment: "none" },
  { name: "Prone Y-T-W Raises", region: "thoracic", type: "strengthening",
    instructions: ["Lie face down with arms overhead in a 'Y'.", "Lift the arms, squeezing the shoulder blades, then lower.", "Repeat with arms out to the side as a 'T', then bent as a 'W'.", "Keep the neck long and gaze down."],
    dosage: "8-10 reps per position, hold 3-5 seconds", frequency: "1x per day",
    tips: "Lead with the shoulder blades, not the hands. Avoid shrugging or arching the low back.", equipment: "none" },
  { name: "Prone Thoracic Extension", region: "thoracic", type: "strengthening",
    instructions: ["Lie face down with hands lightly behind your head.", "Gently lift your chest and upper back off the floor.", "Squeeze the shoulder blades as you rise.", "Lower slowly with control."],
    dosage: "10 reps, hold 3-5 seconds", frequency: "1x per day",
    tips: "Lift from the upper back, keeping the motion small and the neck neutral.", equipment: "none" },
  { name: "Quadruped Thoracic Rotation (Thread the Needle)", region: "thoracic", type: "mobility",
    instructions: ["Start on hands and knees.", "Reach one arm under your body, rotating the upper back.", "Then sweep the same arm up and open toward the ceiling.", "Follow your hand with your eyes and return."],
    dosage: "8-10 reps each side", frequency: "1-2x per day",
    tips: "Keep hips over the knees so the rotation stays in the mid-back.", equipment: "none" },
  { name: "Foam Roller Thoracic Self-Mobilization", region: "thoracic", type: "mobility",
    instructions: ["Lie back with a foam roller across the mid-back.", "Cross arms over your chest and lift hips slightly.", "Slowly roll up and down the upper back.", "Pause on any tight spots for a few breaths."],
    dosage: "60-90 seconds of slow rolling", frequency: "1-2x per day",
    tips: "Stay above the low back; never roll over the neck or lower spine.", equipment: "foam roller" },
  { name: "Standing Rows with Resistance Band", region: "thoracic", type: "strengthening",
    instructions: ["Anchor a band at chest height and hold an end in each hand.", "Stand tall with elbows close to your sides.", "Pull the band back, squeezing the shoulder blades together.", "Slowly return to the start."],
    dosage: "10-15 reps, 2 sets", frequency: "1x per day",
    tips: "Keep shoulders down and away from the ears; control the return.", equipment: "resistance band" },
  { name: "Pectoral Doorway Stretch", region: "thoracic", type: "stretch",
    instructions: ["Stand in a doorway with forearms on the frame, elbows at shoulder height.", "Step one foot forward through the doorway.", "Lean gently until you feel a stretch across the chest and front of the shoulders.", "Hold, then ease back."],
    dosage: "Hold 20-30 seconds, 3 reps", frequency: "1-2x per day",
    tips: "Keep the core gently engaged; stretch should be felt in the chest, not the shoulder joint.", equipment: "none" },
  { name: "Band Pull-Apart", region: "thoracic", type: "strengthening",
    instructions: ["Stand tall holding a resistance band in front of you at chest height, hands shoulder-width apart.", "Keep your arms straight and squeeze your shoulder blades together.", "Pull the band apart until your arms reach out to the sides.", "Slowly return to the start with control."],
    dosage: "10-15 reps, 2 sets", frequency: "1x per day",
    tips: "Keep shoulders down and ribs gently in; lead with the shoulder blades, not the hands.", equipment: "resistance band" },
  { name: "Seated Thoracic Extension over Chair", region: "thoracic", type: "mobility",
    instructions: ["Sit in a firm chair with the backrest hitting your mid-back, hands behind your head.", "Gently extend your upper back backward over the edge of the backrest.", "Look slightly upward and exhale as you arch.", "Return to upright and repeat."],
    dosage: "8-10 reps, hold 2-3 seconds", frequency: "1-2x per day",
    tips: "Move from the mid-back and keep the motion small; do not arch the lower back. Stop if sharp pain.", equipment: "chair" },
  { name: "Sphinx Pose (Thoracic Extension)", region: "thoracic", type: "mobility",
    instructions: ["Lie face down and prop yourself up on your forearms, elbows under your shoulders.", "Gently lift your chest and let your upper back extend.", "Keep your shoulders relaxed away from your ears.", "Hold, breathing gently, then lower."],
    dosage: "Hold 20-30 seconds, 3 reps", frequency: "1-2x per day",
    tips: "Focus the stretch in the mid-back, keeping the low back relaxed. Stop if it causes sharp pain.", equipment: "mat" },

  /* ---------------- LUMBAR ---------------- */
  { name: "Knee to Chest Stretch", region: "lumbar", type: "stretch",
    instructions: ["Lie on your back with knees bent, feet flat.", "Pull one knee toward your chest with both hands.", "Keep the other foot flat or leg extended.", "Slowly lower and switch sides."],
    dosage: "Hold 20-30 seconds, 2-3 reps each side", frequency: "1-2x per day",
    tips: "Keep your lower back and shoulders relaxed on the floor. Stop if you feel sharp pain.", equipment: "none" },
  { name: "Posterior Pelvic Tilt", region: "lumbar", type: "mobility",
    instructions: ["Lie on your back, knees bent, feet flat.", "Gently flatten your lower back into the floor by tightening your stomach.", "Hold briefly, then relax to a neutral spine."],
    dosage: "Hold 5-10 seconds, 10-15 reps", frequency: "1-2x per day",
    tips: "Move only through a comfortable range; breathe normally. Stop if pain sharpens.", equipment: "none" },
  { name: "Cat-Cow", region: "lumbar", type: "mobility",
    instructions: ["Start on hands and knees with a flat back.", "Arch your back upward and tuck your chin (cat).", "Then drop your belly and lift your chest and head (cow).", "Move slowly between positions."],
    dosage: "8-12 slow reps", frequency: "1-2x per day",
    tips: "Let the movement be smooth and pain-free. Stop if sharp pain occurs.", equipment: "none" },
  { name: "Lower Trunk Rotation", region: "lumbar", type: "mobility",
    instructions: ["Lie on your back with knees bent, feet flat.", "Keep shoulders down and gently lower both knees to one side.", "Return to center and repeat to the other side."],
    dosage: "Hold 5 seconds, 8-10 reps each side", frequency: "1-2x per day",
    tips: "Keep both shoulders on the floor. Stop if you feel sharp or radiating pain.", equipment: "none" },
  { name: "Bird Dog", region: "lumbar", type: "strengthening",
    instructions: ["Begin on hands and knees with a neutral spine.", "Extend one arm forward and the opposite leg back.", "Keep your hips level and hold briefly.", "Return and switch sides."],
    dosage: "Hold 5-10 seconds, 8-10 reps each side", frequency: "1x per day",
    tips: "Do not let your low back sag or twist. Stop if pain increases.", equipment: "none" },
  { name: "Glute Bridge", region: "lumbar", type: "strengthening",
    instructions: ["Lie on your back, knees bent, feet flat hip-width apart.", "Tighten your stomach and squeeze your glutes.", "Lift your hips into a straight line from shoulders to knees.", "Lower slowly with control."],
    dosage: "10-15 reps, 2-3 sets", frequency: "1x per day",
    tips: "Lift with your glutes, not your lower back. Stop if pain sharpens.", equipment: "none" },
  { name: "McGill Curl-Up", region: "lumbar", type: "strengthening",
    instructions: ["Lie on your back with one knee bent, the other straight.", "Place both hands under your lower back to preserve its natural curve.", "Brace your abdominals and raise your head and shoulders only a small distance, leading with the chest.", "Keep your low back still (do not flatten or round it), then lower slowly."],
    dosage: "8-12 reps, 2-3 sets", frequency: "1x per day",
    tips: "This is not a sit-up: the low back should not flex or press flat. Keep the lift small, don't pull on your neck, and stop if pain occurs.", equipment: "none" },
  { name: "Prone Press-Up (Extension)", region: "lumbar", type: "mobility",
    instructions: ["Lie face down with hands flat under your shoulders.", "Press your upper body up, keeping hips on the floor.", "Let your lower back relax as it arches.", "Lower slowly."],
    dosage: "Hold 2-5 seconds, 8-10 reps", frequency: "Several times per day as advised",
    tips: "Stop if it increases leg symptoms or causes sharp pain.", equipment: "none" },
  { name: "McKenzie Press-Up (Extension in Lying)", region: "lumbar", type: "mobility",
    instructions: ["Lie face down, hands flat under your shoulders.", "Press your upper body up, straightening your arms as far as comfortable.", "Keep your hips, pelvis, and legs relaxed on the floor.", "Lower slowly; over sets, aim to press a little higher."],
    dosage: "10 reps, hold 1-2 seconds at the top", frequency: "Every 2-3 hours as advised",
    tips: "Let your arms do the lifting while your back stays relaxed. Stop if symptoms spread down the leg.", equipment: "none" },
  { name: "Side Plank", region: "lumbar", type: "strengthening",
    instructions: ["Lie on your side, propped on your forearm.", "Stack your knees or feet and tighten your core.", "Lift your hips to form a straight line.", "Hold, then lower and switch sides."],
    dosage: "Hold 10-20 seconds, 3 reps each side", frequency: "1x per day",
    tips: "Start from the knees if a full plank is too hard. Stop if pain sharpens.", equipment: "none" },
  { name: "Child's Pose", region: "lumbar", type: "stretch",
    instructions: ["Kneel and sit your hips back toward your heels.", "Reach your arms forward and lower your chest.", "Relax and breathe into your lower back."],
    dosage: "Hold 20-30 seconds, 2-3 reps", frequency: "1-2x per day",
    tips: "Widen your knees if it eases pressure. Stop if knees or back hurt sharply.", equipment: "none" },
  { name: "Double Knee to Chest", region: "lumbar", type: "stretch",
    instructions: ["Lie on your back with knees bent.", "Pull both knees gently toward your chest.", "Hold, then slowly lower your feet back down."],
    dosage: "Hold 20-30 seconds, 2-3 reps", frequency: "1-2x per day",
    tips: "Move gently and keep your head relaxed on the floor. Stop if pain sharpens.", equipment: "none" },
  { name: "Dead Bug", region: "lumbar", type: "strengthening",
    instructions: ["Lie on your back with arms reaching toward the ceiling and knees bent at 90 degrees over your hips.", "Gently flatten your low back into the floor and brace your core.", "Slowly lower one arm overhead and the opposite leg toward the floor.", "Return to start and switch to the other side."],
    dosage: "8-10 reps each side", frequency: "1x per day",
    tips: "Keep your low back pressed to the floor the whole time; move slowly. Stop if your back arches or pain occurs.", equipment: "none" },
  { name: "Standing Lumbar Extension", region: "lumbar", type: "mobility",
    instructions: ["Stand tall with your feet shoulder-width apart.", "Place both hands on your lower back, fingers pointing down.", "Gently lean backward, bending over your hands.", "Return to upright and repeat."],
    dosage: "10 reps, hold 1-2 seconds", frequency: "Several times per day as advised",
    tips: "Useful as a posture reset after prolonged sitting. Stop if it increases leg symptoms or causes sharp pain.", equipment: "none" },
  { name: "Hip Hinge (Hinge Pattern Training)", region: "lumbar", type: "strengthening",
    instructions: ["Stand tall holding a stick or dowel along your spine, touching head, mid-back, and tailbone.", "Push your hips straight back while keeping your back flat and knees softly bent.", "Lower your chest forward only as far as your back stays straight.", "Squeeze your glutes to return to standing."],
    dosage: "10-12 reps, 2 sets", frequency: "1x per day",
    tips: "Keep all three contact points on the stick to protect a neutral spine. Stop if sharp pain occurs.", equipment: "stick / dowel" },

  /* ---------------- HIP ---------------- */
  { name: "Piriformis (Figure-Four) Stretch", region: "hip", type: "stretch",
    instructions: ["Lie on your back with both knees bent.", "Cross one ankle over the opposite thigh.", "Pull the bottom thigh toward your chest.", "Hold, then switch sides."],
    dosage: "Hold 30 seconds, 2-3 reps each side", frequency: "1-2x per day",
    tips: "Feel the stretch deep in the buttock, not the knee. Stop if pain is sharp.", equipment: "none" },
  { name: "Kneeling Hip Flexor Stretch", region: "hip", type: "stretch",
    instructions: ["Kneel on one knee with the other foot flat in front.", "Tuck your pelvis and gently shift your weight forward.", "Keep your torso upright until you feel a front-hip stretch.", "Switch sides."],
    dosage: "Hold 30 seconds, 2-3 reps each side", frequency: "1-2x per day",
    tips: "Use a cushion under the knee and avoid arching your back. Stop if pain sharpens.", equipment: "none" },
  { name: "Clamshell", region: "hip", type: "strengthening",
    instructions: ["Lie on your side with knees bent and stacked.", "Keep your feet together and core tight.", "Lift the top knee while keeping hips still.", "Lower slowly and repeat, then switch sides."],
    dosage: "10-15 reps, 2-3 sets each side", frequency: "1x per day",
    tips: "Do not let your top hip roll backward. Stop if pain occurs.", equipment: "none" },
  { name: "Side-Lying Hip Abduction", region: "hip", type: "strengthening",
    instructions: ["Lie on your side with legs straight, stacked.", "Keep your top leg straight and toes facing forward.", "Lift the top leg upward, then lower slowly.", "Switch sides."],
    dosage: "10-15 reps, 2-3 sets each side", frequency: "1x per day",
    tips: "Lift with the side of your hip, not by rolling back. Stop if pain sharpens.", equipment: "none" },
  { name: "Glute Bridge", region: "hip", type: "strengthening",
    instructions: ["Lie on your back, knees bent, feet flat hip-width apart.", "Squeeze your glutes and lift your hips.", "Form a straight line from shoulders to knees.", "Lower slowly."],
    dosage: "10-15 reps, 2-3 sets", frequency: "1x per day",
    tips: "Drive through your heels and avoid arching the low back. Stop if pain occurs.", equipment: "none" },
  { name: "Standing Hip Abduction", region: "hip", type: "strengthening",
    instructions: ["Stand tall holding a chair for balance.", "Keep your leg straight and toes forward.", "Lift the leg out to the side, then lower slowly.", "Switch sides."],
    dosage: "10-15 reps, 2-3 sets each side", frequency: "1x per day",
    tips: "Keep your torso upright and avoid leaning. Stop if pain sharpens.", equipment: "none" },
  { name: "Seated Piriformis / Glute Stretch", region: "hip", type: "stretch",
    instructions: ["Sit tall in a chair with both feet flat.", "Cross one ankle over the opposite knee.", "Gently lean forward from the hips.", "Hold, then switch sides."],
    dosage: "Hold 30 seconds, 2-3 reps each side", frequency: "1-2x per day",
    tips: "Keep your back straight as you lean. Stop if you feel sharp pain.", equipment: "none" },
  { name: "Hip Flexion Marching", region: "hip", type: "mobility",
    instructions: ["Sit or stand tall with good posture.", "Lift one knee up toward your chest.", "Lower with control and alternate legs."],
    dosage: "10-15 reps each side, 2 sets", frequency: "1x per day",
    tips: "Move smoothly and keep your trunk upright. Stop if pain sharpens.", equipment: "none" },
  { name: "Standing Hip Extension", region: "hip", type: "strengthening",
    instructions: ["Stand tall holding a chair for balance.", "Keep your leg straight and core tight.", "Move the leg backward without arching your back.", "Lower slowly and switch sides."],
    dosage: "10-15 reps, 2-3 sets each side", frequency: "1x per day",
    tips: "Squeeze the glute and avoid leaning forward. Stop if pain occurs.", equipment: "none" },
  { name: "Hip Adduction Squeeze", region: "hip", type: "strengthening",
    instructions: ["Lie on your back with knees bent, feet flat.", "Place a pillow or ball between your knees.", "Squeeze the knees together and hold.", "Relax slowly."],
    dosage: "Hold 5-10 seconds, 10-15 reps", frequency: "1x per day",
    tips: "Keep your back relaxed and breathe normally. Stop if pain sharpens.", equipment: "pillow / ball" },
  { name: "Hip Internal/External Rotation Mobility", region: "hip", type: "mobility",
    instructions: ["Sit with knees bent and feet wider than hips.", "Gently drop both knees inward, then outward.", "Move slowly through a comfortable range."],
    dosage: "10-12 reps each direction", frequency: "1-2x per day",
    tips: "Stay within a pain-free range. Stop if you feel pinching or sharp pain.", equipment: "none" },
  { name: "Pigeon Pose (Hip Stretch)", region: "hip", type: "stretch",
    instructions: ["Start on hands and knees.", "Bring one knee forward toward the same-side wrist, shin angled across.", "Slide the other leg straight back and lower your hips toward the floor.", "Keep hips level; ease your chest down for a deeper stretch."],
    dosage: "Hold 30 seconds, 2-3 reps each side", frequency: "1-2x per day",
    tips: "Keep the front shin comfortable and your hips square. Stop if you feel knee pain.", equipment: "mat" },
  { name: "Fire Hydrant", region: "hip", type: "strengthening",
    instructions: ["Start on hands and knees with a neutral spine and core braced.", "Keeping the knee bent at 90 degrees, lift one leg out to the side.", "Raise it to hip height without rotating your trunk.", "Lower slowly and repeat, then switch sides."],
    dosage: "10-15 reps, 2-3 sets each side", frequency: "1x per day",
    tips: "Keep your back flat and hips level; do not lean to the opposite side. Stop if pain sharpens.", equipment: "none" },
  { name: "Lateral Band Walk (Monster Walk)", region: "hip", type: "strengthening",
    instructions: ["Place a resistance band around your legs just above the knees or ankles.", "Stand in a quarter-squat with feet hip-width and knees over toes.", "Step sideways one foot at a time, keeping tension on the band.", "Take several steps one way, then return the other way."],
    dosage: "10-12 steps each direction, 2-3 sets", frequency: "1x per day",
    tips: "Keep knees pushed apart and stay low; do not let knees cave inward. Stop if pain sharpens.", equipment: "resistance band" },
  { name: "90/90 Hip Stretch", region: "hip", type: "stretch",
    instructions: ["Sit on the floor with one leg in front bent 90 degrees and the other out to the side bent 90 degrees.", "Square your shoulders over the front shin and sit tall.", "Gently lean your chest forward over the front leg.", "Hold, then switch leg positions for the other side."],
    dosage: "Hold 30 seconds, 2-3 reps each side", frequency: "1-2x per day",
    tips: "Keep both sitting bones down and the spine long. Stop if you feel pinching in the front of the hip or knee pain.", equipment: "mat" },
  { name: "Glute Bridge with March", region: "hip", type: "strengthening",
    instructions: ["Lie on your back, knees bent, feet flat, and lift into a glute bridge.", "Hold your hips level and brace your core.", "Slowly lift one foot a few inches, then return it and lift the other.", "Lower your hips only after completing the marches."],
    dosage: "8-10 marches each side", frequency: "1x per day",
    tips: "Keep your hips from dropping or rocking as you march. Stop if pain occurs in the back or hip.", equipment: "none" },

  /* ---------------- SHOULDER ---------------- */
  { name: "Pendulum Swings (Codman's)", region: "shoulder", type: "mobility",
    instructions: ["Lean forward, supporting your good arm on a table or chair.", "Let the affected arm hang straight down and relaxed.", "Gently swing the arm in small circles, then forward/back and side to side."],
    dosage: "10 circles each direction, 1-2 minutes total", frequency: "2-3x per day",
    tips: "Let gravity and body sway do the work; keep shoulder muscles relaxed. Stop if sharp pain.", equipment: "none" },
  { name: "Cross-Body Posterior Shoulder Stretch", region: "shoulder", type: "stretch",
    instructions: ["Bring the affected arm across the front of your chest at shoulder height.", "Use the opposite hand to gently pull the arm closer at the elbow.", "Hold and feel a stretch in the back of the shoulder."],
    dosage: "Hold 30 seconds, 3-4 reps", frequency: "2x per day",
    tips: "Pull at the elbow, not the wrist. Feel a stretch, not pinching. Stop if sharp pain.", equipment: "none" },
  { name: "Doorway Pectoral Stretch", region: "shoulder", type: "stretch",
    instructions: ["Stand in a doorway with forearms on the frame, elbows at shoulder height.", "Step one foot forward through the doorway.", "Lean gently until you feel a stretch across the chest and front of shoulders."],
    dosage: "Hold 30 seconds, 3 reps", frequency: "1-2x per day",
    tips: "Keep your core tight and avoid arching your low back. Stop if sharp pain.", equipment: "none" },
  { name: "Sleeper Stretch", region: "shoulder", type: "stretch",
    instructions: ["Lie on your side on the affected shoulder, elbow bent to 90 degrees out front.", "Use the top hand to gently push the affected forearm down toward the floor.", "Hold at a comfortable stretch in the back of the shoulder."],
    dosage: "Hold 30 seconds, 3 reps", frequency: "1-2x per day",
    tips: "Apply gentle, slow pressure; never force into pinching pain. Stop if sharp pain.", equipment: "none" },
  { name: "Towel Internal Rotation Stretch", region: "shoulder", type: "mobility",
    instructions: ["Hold a towel behind your back, top hand over the shoulder, bottom hand at the low back.", "Gently pull upward with the top hand to raise the bottom arm up your back.", "Hold, then switch the towel direction to stretch the other way."],
    dosage: "Hold 20-30 seconds, 3-4 reps each way", frequency: "1-2x per day",
    tips: "Move slowly and stay within a comfortable range. Stop if sharp pain.", equipment: "towel" },
  { name: "Scapular Squeezes (Retraction)", region: "shoulder", type: "strengthening",
    instructions: ["Sit or stand tall with arms relaxed at your sides.", "Gently squeeze your shoulder blades together and slightly down.", "Hold briefly, then relax."],
    dosage: "2-3 sets of 10, hold 5 seconds each", frequency: "1-2x per day",
    tips: "Keep shoulders down and avoid shrugging toward your ears. Stop if sharp pain.", equipment: "none" },
  { name: "Resisted External Rotation", region: "shoulder", type: "strengthening",
    instructions: ["Anchor a band at waist height; stand with the affected side away from it.", "Keep your elbow bent 90 degrees and tucked against your side (a towel roll helps).", "Rotate your forearm outward away from your stomach, then slowly return."],
    dosage: "2-3 sets of 10-15 reps", frequency: "Every other day",
    tips: "Keep the elbow pinned to your side and move only the forearm. Stop if sharp pain.", equipment: "resistance band" },
  { name: "Resisted Internal Rotation", region: "shoulder", type: "strengthening",
    instructions: ["Anchor a band at waist height; stand with the affected side toward it.", "Keep your elbow bent 90 degrees and tucked against your side.", "Pull your forearm inward across your stomach, then slowly return."],
    dosage: "2-3 sets of 10-15 reps", frequency: "Every other day",
    tips: "Keep the elbow tucked and avoid twisting your torso. Stop if sharp pain.", equipment: "resistance band" },
  { name: "Resisted Rows (Scapular Strengthening)", region: "shoulder", type: "strengthening",
    instructions: ["Anchor a band in front of you at chest height and hold an end in each hand.", "Pull your elbows straight back, squeezing your shoulder blades together.", "Slowly return to the start with control."],
    dosage: "3 sets of 10-12 reps", frequency: "Every other day",
    tips: "Lead with the elbows and keep shoulders relaxed, not shrugged. Stop if sharp pain.", equipment: "resistance band" },
  { name: "Wall Slides (Scaption)", region: "shoulder", type: "mobility",
    instructions: ["Stand facing a wall with forearms resting against it, elbows bent.", "Slowly slide your forearms upward along the wall as far as comfortable.", "Lower back down with control."],
    dosage: "2 sets of 10 reps", frequency: "1-2x per day",
    tips: "Keep shoulders down and avoid shrugging as you reach overhead. Stop if sharp pain.", equipment: "none" },
  { name: "Prone Y and T Raises", region: "shoulder", type: "strengthening",
    instructions: ["Lie face down with arms hanging toward the floor.", "Raise arms into a Y overhead, then a T out to the sides, squeezing shoulder blades.", "Lower slowly with control between reps."],
    dosage: "2 sets of 10 reps each position", frequency: "Every other day",
    tips: "Use light or no weight at first and keep movements slow. Stop if sharp pain.", equipment: "light weight" },
  { name: "Scaption Raise", region: "shoulder", type: "strengthening",
    instructions: ["Stand tall holding a light weight in each hand, thumbs pointing up.", "Raise your arms out at about a 30-45 degree angle in front of you (the 'scaption' plane).", "Lift to about shoulder height, no higher.", "Lower slowly with control."],
    dosage: "2 sets of 10-12 reps", frequency: "Every other day",
    tips: "Keep thumbs up and stop at shoulder height; do not shrug. Stop if sharp pain or pinching.", equipment: "light weight" },
  { name: "Side-Lying External Rotation", region: "shoulder", type: "strengthening",
    instructions: ["Lie on your uninvolved side with the top (involved) arm along your body, elbow bent 90 degrees.", "Tuck a small towel roll between your elbow and your side.", "Keeping the elbow tucked, rotate the forearm and weight upward toward the ceiling.", "Lower slowly back toward your stomach."],
    dosage: "2-3 sets of 10-15 reps", frequency: "Every other day",
    tips: "Keep the elbow pinned to your side and move only the forearm. Stop if sharp pain.", equipment: "light weight" },
  { name: "Serratus Punch (Scapular Protraction)", region: "shoulder", type: "strengthening",
    instructions: ["Lie on your back holding a light weight with the arm pointed straight up toward the ceiling.", "Keep the elbow straight and reach the weight upward, lifting the shoulder blade off the floor.", "Hold briefly at the top of the reach.", "Lower the shoulder blade back down slowly."],
    dosage: "2 sets of 10-12 reps", frequency: "Every other day",
    tips: "The motion is a small shoulder-blade reach, not an elbow bend. Stop if sharp pain.", equipment: "light weight" },
  { name: "Prone Horizontal Abduction", region: "shoulder", type: "strengthening",
    instructions: ["Lie face down on a bed with the involved arm hanging off the edge, thumb pointing forward.", "Keep the elbow straight and raise the arm out to the side to shoulder height.", "Squeeze the shoulder blade as you lift.", "Lower slowly with control."],
    dosage: "2 sets of 10-12 reps", frequency: "Every other day",
    tips: "Lead with the shoulder blade and use light or no weight to start. Stop if sharp pain.", equipment: "light weight" },

  /* ---------------- ELBOW ---------------- */
  { name: "Wrist Flexor Stretch", region: "elbow", type: "stretch",
    instructions: ["Extend the affected arm straight out with the palm facing up.", "Use the other hand to gently pull the fingers and wrist downward.", "Hold where you feel a stretch in the inner forearm."],
    dosage: "Hold 30-45 seconds, 3 reps", frequency: "2x per day",
    tips: "Keep the elbow straight for a fuller stretch. Stop if sharp pain.", equipment: "none" },
  { name: "Wrist Extensor Stretch", region: "elbow", type: "stretch",
    instructions: ["Extend the affected arm straight out with the palm facing down.", "Use the other hand to gently bend the wrist downward toward the floor.", "Hold where you feel a stretch in the outer forearm."],
    dosage: "Hold 30-45 seconds, 3 reps", frequency: "2x per day",
    tips: "Keep the elbow straight and the stretch gentle, not painful. Stop if sharp pain.", equipment: "none" },
  { name: "Eccentric Wrist Extension", region: "elbow", type: "strengthening",
    instructions: ["Rest the forearm on a table, palm down, hand off the edge holding a light weight.", "Use the other hand to help lift the weight into an extended (up) position.", "Remove the helping hand and slowly lower the weight over 3-4 seconds."],
    dosage: "3 sets of 15 reps", frequency: "1x per day (5-6 days/week)",
    tips: "Focus on the slow lowering phase; this loads the tennis-elbow tendon. Stop if sharp pain.", equipment: "light weight" },
  { name: "Eccentric Wrist Flexion", region: "elbow", type: "strengthening",
    instructions: ["Rest the forearm on a table, palm up, hand off the edge holding a light weight.", "Use the other hand to help curl the weight up into flexion.", "Remove the helping hand and slowly lower the weight over 3-4 seconds."],
    dosage: "3 sets of 15 reps", frequency: "1x per day (5-6 days/week)",
    tips: "The slow lowering targets the golfer's-elbow tendon. Stop if sharp pain.", equipment: "light weight" },
  { name: "Tyler Twist (FlexBar Eccentric)", region: "elbow", type: "strengthening",
    instructions: ["Hold the FlexBar vertically, gripping the bottom with the painful (extensor) side.", "Twist the top with the other hand, then hold the bar out horizontally in front.", "Slowly untwist the bar over 3-4 seconds using the affected wrist."],
    dosage: "3 sets of 15 reps", frequency: "1x per day",
    tips: "For tennis elbow; progress bar color when 3 sets of 15 feel easy. Stop if sharp pain.", equipment: "resistance bar" },
  { name: "Reverse Tyler Twist (FlexBar)", region: "elbow", type: "strengthening",
    instructions: ["Hold the FlexBar with the painful (flexor) side gripping the bar, palm up.", "Twist the bar with the opposite hand and extend both arms in front.", "Slowly let the affected wrist untwist the bar with control."],
    dosage: "3 sets of 15 reps", frequency: "1x per day",
    tips: "For golfer's elbow; keep the motion slow and controlled. Stop if sharp pain.", equipment: "resistance bar" },
  { name: "Forearm Pronation / Supination", region: "elbow", type: "mobility",
    instructions: ["Rest the forearm on a table with the wrist and hand off the edge.", "Hold a light weight or hammer and slowly turn the palm up.", "Then slowly rotate the palm down; repeat smoothly."],
    dosage: "2-3 sets of 15 reps", frequency: "1x per day",
    tips: "Keep the elbow tucked at your side and move only the forearm. Stop if sharp pain.", equipment: "light weight" },
  { name: "Grip Strengthening (Ball Squeeze)", region: "elbow", type: "strengthening",
    instructions: ["Hold a soft ball or rolled towel in the affected hand.", "Squeeze firmly and hold.", "Release slowly and relax between reps."],
    dosage: "2-3 sets of 10-15 reps, hold 5 seconds", frequency: "1-2x per day",
    tips: "Squeeze to a firm but pain-free effort. Stop if sharp pain.", equipment: "ball" },
  { name: "Elbow Flexion / Extension ROM", region: "elbow", type: "mobility",
    instructions: ["Sit or stand with the arm relaxed at your side.", "Slowly bend the elbow to bring your hand toward your shoulder.", "Slowly straighten the elbow fully; repeat."],
    dosage: "2 sets of 10-15 reps", frequency: "2-3x per day",
    tips: "Move gently through the full pain-free range. Stop if sharp pain.", equipment: "none" },
  { name: "Biceps Curl", region: "elbow", type: "strengthening",
    instructions: ["Stand or sit holding a light weight, palm facing up, elbow at your side.", "Bend the elbow to curl the weight toward your shoulder.", "Lower slowly with control to fully straight."],
    dosage: "2-3 sets of 10-12 reps", frequency: "Every other day",
    tips: "Keep the elbow tucked and avoid swinging the weight. Stop if sharp pain.", equipment: "light weight" },
  { name: "Radial Nerve Glide", region: "elbow", type: "mobility",
    instructions: ["Stand tall and reach the affected arm down and slightly behind you, palm facing back.", "Make a loose fist and bend the wrist downward.", "Gently tilt your head away to the opposite side to add a light glide.", "Return to neutral and repeat smoothly."],
    dosage: "5-10 reps through the sequence", frequency: "2-3x per day",
    tips: "Glide gently; this should not provoke tingling or pain. Stop if numbness increases.", equipment: "none" },
  { name: "Ulnar Nerve Glide", region: "elbow", type: "mobility",
    instructions: ["Raise the affected arm out to the side with the palm up.", "Bend the elbow and wrist, bringing the fingers toward your face like a mask.", "Make an 'OK' sign with thumb and index finger around the eye.", "Slowly straighten and return; repeat smoothly."],
    dosage: "5-10 reps through the sequence", frequency: "2-3x per day",
    tips: "Move gently and stop short of tingling; helpful for cubital tunnel symptoms. Stop if numbness increases.", equipment: "none" },
  { name: "Wrist Roller", region: "elbow", type: "strengthening",
    instructions: ["Hold a wrist roller or a dowel with a cord and light weight at arm's length, palms down.", "Roll the weight up by alternately turning the wrists.", "Once fully raised, slowly reverse to lower the weight.", "Rest and repeat."],
    dosage: "2-3 roll-ups and roll-downs", frequency: "Every other day",
    tips: "Keep elbows fairly still and use a light weight to build forearm endurance. Stop if sharp pain.", equipment: "wrist roller" },

  /* ---------------- WRIST ---------------- */
  { name: "Median Nerve Glide", region: "wrist", type: "mobility",
    instructions: ["Make a fist with the thumb on the outside, wrist neutral.", "Straighten the fingers and wrist, then gently bend the wrist back and extend the thumb.", "Move smoothly through the positions and return."],
    dosage: "5-10 reps through the sequence", frequency: "2-3x per day",
    tips: "Glide gently; this should not produce tingling or pain. Stop if numbness increases.", equipment: "none" },
  { name: "Tendon Glide", region: "wrist", type: "mobility",
    instructions: ["Start with fingers straight out.", "Bend into a hook fist, then a full fist, then a straight (tabletop) fist.", "Return to straight fingers between each position."],
    dosage: "5-10 reps through each position", frequency: "2-3x per day",
    tips: "Move slowly and keep it pain-free; helps tendons glide in the carpal tunnel. Stop if sharp pain.", equipment: "none" },
  { name: "Wrist Flexor Stretch", region: "wrist", type: "stretch",
    instructions: ["Extend the affected arm in front with the elbow straight, palm up.", "Use the other hand to gently pull the fingers and wrist down toward the floor.", "Hold when you feel a stretch in the forearm, then release."],
    dosage: "Hold 15-30 seconds, 2-4 reps", frequency: "2-3x per day",
    tips: "Apply gentle pressure only; keep the elbow straight. Stop if sharp pain.", equipment: "none" },
  { name: "Wrist Extensor Stretch", region: "wrist", type: "stretch",
    instructions: ["Extend the affected arm in front with the elbow straight, palm down.", "Use the other hand to gently bend the wrist so fingers point toward the floor.", "Hold when you feel a stretch on top of the forearm, then release."],
    dosage: "Hold 15-30 seconds, 2-4 reps", frequency: "2-3x per day",
    tips: "Stretch should feel gentle, not painful. Helpful for wrist tendinopathy. Stop if sharp pain.", equipment: "none" },
  { name: "Prayer Stretch", region: "wrist", type: "stretch",
    instructions: ["Place palms together in front of your chest, fingers pointing up.", "Slowly lower your hands toward your waist, keeping palms pressed together.", "Hold when you feel a stretch in the wrists and forearms."],
    dosage: "Hold 15-30 seconds, 2-3 reps", frequency: "2-3x per day",
    tips: "Keep your shoulders relaxed and palms flat together. Stop if sharp pain.", equipment: "none" },
  { name: "Wrist Flexion / Extension Active ROM", region: "wrist", type: "mobility",
    instructions: ["Rest your forearm on a table with your hand off the edge, palm down.", "Bend the wrist up as far as comfortable, then down as far as comfortable.", "Move slowly and smoothly through the full pain-free range."],
    dosage: "10-15 reps each direction", frequency: "2-3x per day",
    tips: "Move only the wrist, keeping the forearm still on the table. Stop if sharp pain.", equipment: "none" },
  { name: "Forearm Pronation / Supination", region: "wrist", type: "mobility",
    instructions: ["Bend your elbow to 90 degrees, tucked at your side, holding a light weight or pen.", "Slowly rotate your palm up, then rotate it down.", "Repeat through a smooth, pain-free range."],
    dosage: "10-15 reps each direction", frequency: "2x per day",
    tips: "Keep the elbow tucked against your side so only the forearm rotates. Stop if sharp pain.", equipment: "light weight" },
  { name: "Wrist Curl (Flexion Strengthening)", region: "wrist", type: "strengthening",
    instructions: ["Rest your forearm on a table, palm up, hand off the edge holding a light weight.", "Curl the wrist upward, lifting the weight.", "Lower slowly back down."],
    dosage: "10-15 reps, 2-3 sets", frequency: "1x per day",
    tips: "Start with a very light weight and move only the wrist. Stop if sharp pain.", equipment: "light weight" },
  { name: "Reverse Wrist Curl (Extension Strengthening)", region: "wrist", type: "strengthening",
    instructions: ["Rest your forearm on a table, palm down, hand off the edge holding a light weight.", "Lift the back of the hand upward.", "Lower slowly back down with control."],
    dosage: "10-15 reps, 2-3 sets", frequency: "1x per day",
    tips: "Use a light weight; strengthens muscles for wrist tendinopathy. Stop if sharp pain.", equipment: "light weight" },
  { name: "Grip Strengthening", region: "wrist", type: "strengthening",
    instructions: ["Hold a soft stress ball or rolled towel in your palm.", "Squeeze firmly and hold.", "Fully relax your grip."],
    dosage: "10-15 reps, hold 3-5 seconds", frequency: "1-2x per day",
    tips: "Use a soft ball, not a hard one. Avoid if it increases numbness or tingling. Stop if sharp pain.", equipment: "stress ball" },
  { name: "Radial and Ulnar Deviation", region: "wrist", type: "mobility",
    instructions: ["Rest your forearm on a table with the wrist neutral, thumb pointing up.", "Move the hand toward the thumb side, then toward the little-finger side.", "Keep the motion slow and within a pain-free range."],
    dosage: "10-15 reps each direction", frequency: "2x per day",
    tips: "Move only at the wrist, keeping the forearm anchored. Stop if sharp pain.", equipment: "none" },
  { name: "Thumb Stretch (Opposition and Extension)", region: "wrist", type: "stretch",
    instructions: ["Hold the affected hand up with fingers relaxed.", "Gently touch the thumb tip to the base of the little finger, feeling a stretch.", "Then use the other hand to gently draw the thumb outward and back.", "Hold each position, then relax."],
    dosage: "Hold 10-15 seconds, 3-5 reps each", frequency: "2-3x per day",
    tips: "Move gently; useful for thumb arthritis and de Quervain's stiffness. Stop if sharp pain.", equipment: "none" },
  { name: "Finger Extension with Rubber Band", region: "wrist", type: "strengthening",
    instructions: ["Place a rubber band around the outside of your fingers and thumb.", "Rest the hand on a table with fingers lightly bunched.", "Spread your fingers and thumb apart against the band's resistance.", "Slowly bring them back together."],
    dosage: "10-15 reps, 2-3 sets", frequency: "1x per day",
    tips: "Use a band light enough to control; balances the strong gripping muscles. Stop if sharp pain.", equipment: "rubber band" },
  { name: "Therapy Putty Squeeze and Pinch", region: "wrist", type: "strengthening",
    instructions: ["Hold a ball of therapy putty in the affected hand.", "Squeeze the putty fully with all fingers, then release.", "Next, pinch the putty between the thumb and each fingertip in turn.", "Reshape the putty and repeat."],
    dosage: "10-15 reps of each, 1-2 sets", frequency: "1x per day",
    tips: "Work to a firm but comfortable effort; great for grip and pinch recovery. Avoid if it increases numbness. Stop if sharp pain.", equipment: "therapy putty" },

  /* ---------------- KNEE ---------------- */
  { name: "Quad Set", region: "knee", type: "strengthening",
    instructions: ["Sit or lie with your leg straight out in front of you.", "Tighten the muscle on top of your thigh, pushing the back of your knee down.", "Hold, then fully relax."],
    dosage: "10 reps, hold 5-10 seconds", frequency: "3x per day",
    tips: "Keep the knee straight, not bent. Feel the thigh firm up, not pain. Stop if sharp pain.", equipment: "none" },
  { name: "Straight Leg Raise", region: "knee", type: "strengthening",
    instructions: ["Lie on your back, bend the uninvolved knee with that foot flat on the floor.", "Tighten the thigh of the straight leg and lift it about 8-12 inches.", "Hold briefly, then lower slowly with control."],
    dosage: "10-15 reps, 2-3 sets", frequency: "1-2x per day",
    tips: "Keep the knee locked straight and the thigh tight. Avoid arching your back. Stop if sharp pain.", equipment: "none" },
  { name: "Heel Slide", region: "knee", type: "mobility",
    instructions: ["Lie on your back with both legs straight.", "Slowly slide the heel of the involved leg toward your buttock, bending the knee.", "Slide the heel back down to straighten the knee."],
    dosage: "10-15 reps", frequency: "2-3x per day",
    tips: "Move only into a gentle stretch, never into pain. Stop if sharp pain.", equipment: "none" },
  { name: "Standing Hamstring Stretch", region: "knee", type: "stretch",
    instructions: ["Place your heel on a low step or chair with toes pointing up.", "Keep your back straight and gently hinge forward at the hips.", "Hold when you feel a stretch behind the thigh, then return upright."],
    dosage: "Hold 20-30 seconds, 2-3 reps each leg", frequency: "1-2x per day",
    tips: "Lead with your chest, not your head, and keep the standing knee soft. Stop if sharp pain.", equipment: "none" },
  { name: "Standing Quadriceps Stretch", region: "knee", type: "stretch",
    instructions: ["Stand holding a wall or chair for balance.", "Bend one knee and grasp your ankle, drawing the heel toward your buttock.", "Keep knees together until you feel a stretch in the front of the thigh, then hold."],
    dosage: "Hold 20-30 seconds, 2-3 reps each leg", frequency: "1-2x per day",
    tips: "Keep your hips level and avoid arching your low back. Stop if sharp pain.", equipment: "none" },
  { name: "Calf Stretch", region: "knee", type: "stretch",
    instructions: ["Stand facing a wall with hands on it for support.", "Step one foot back, keeping that leg straight and the heel down.", "Lean forward, bending the front knee, until you feel a stretch in the back calf."],
    dosage: "Hold 20-30 seconds, 2 reps each leg", frequency: "1-2x per day",
    tips: "Keep the back heel pressed flat and toes pointing forward. Stop if sharp pain.", equipment: "none" },
  { name: "Clamshell", region: "knee", type: "strengthening",
    instructions: ["Lie on your side with hips and knees bent, knees stacked.", "Keep feet together and lift the top knee like a clamshell opening.", "Lower the knee slowly back down."],
    dosage: "10-15 reps, 2-3 sets each side", frequency: "1x per day",
    tips: "Keep your pelvis still; don't roll backward. Strong hips support the kneecap. Stop if sharp pain.", equipment: "none" },
  { name: "Wall Sit", region: "knee", type: "strengthening",
    instructions: ["Stand with your back flat against a wall, feet shoulder-width and a step forward.", "Slide down into a partial squat, keeping knees behind your toes.", "Hold the position, then slide back up."],
    dosage: "Hold 10-30 seconds, 3-5 reps", frequency: "1x per day",
    tips: "Do not let knees pass your toes or drop below 90 degrees if it hurts. Stop if sharp pain.", equipment: "none" },
  { name: "Mini Squat", region: "knee", type: "strengthening",
    instructions: ["Stand with feet shoulder-width apart, holding a counter for balance if needed.", "Bend your hips and knees to lower a short way, as if sitting back into a chair.", "Push through your heels to stand back up."],
    dosage: "10-15 reps, 2-3 sets", frequency: "1x per day",
    tips: "Keep knees tracking over your toes, not caving inward. Only go as deep as is pain-free.", equipment: "none" },
  { name: "Step-Up", region: "knee", type: "strengthening",
    instructions: ["Stand facing a low, sturdy step.", "Step up with the involved leg, bringing the other foot to meet it.", "Step back down slowly, leading with the same leg."],
    dosage: "10 reps, 2 sets each leg", frequency: "1x per day",
    tips: "Control the lowering phase and keep the kneecap aligned over the foot. Start with a low step.", equipment: "none" },
  { name: "Hamstring Curl with Resistance Band", region: "knee", type: "strengthening",
    instructions: ["Stand holding a chair, with a band anchored low around your ankle.", "Bend the knee to curl your heel toward your buttock.", "Lower slowly back to the start."],
    dosage: "10-15 reps, 2-3 sets each leg", frequency: "1x per day",
    tips: "Keep your thighs aligned and move only at the knee. Stop if sharp pain.", equipment: "resistance band" },
  { name: "Terminal Knee Extension (Band)", region: "knee", type: "strengthening",
    instructions: ["Anchor a resistance band to a sturdy object and loop it behind the involved knee.", "Stand facing the anchor with a slight bend in the knee and band tension.", "Straighten the knee fully by squeezing the thigh.", "Slowly bend the knee back to the start."],
    dosage: "10-15 reps, 2-3 sets", frequency: "1x per day",
    tips: "Focus on locking out the last few degrees and squeezing the quad. Stop if sharp pain.", equipment: "resistance band" },
  { name: "Prone Hamstring Curl", region: "knee", type: "strengthening",
    instructions: ["Lie face down with both legs straight.", "Bend the involved knee to bring the heel toward your buttock.", "Lift only as far as is comfortable.", "Lower the foot slowly back to the floor."],
    dosage: "10-15 reps, 2-3 sets each leg", frequency: "1x per day",
    tips: "Keep your hips flat on the floor and avoid arching the low back. Stop if sharp pain.", equipment: "none" },
  { name: "Single-Leg Balance", region: "knee", type: "mobility",
    instructions: ["Stand tall near a counter or wall for support if needed.", "Shift your weight onto the involved leg and lift the other foot off the floor.", "Hold your balance with the knee softly bent.", "Lower and repeat, then switch legs."],
    dosage: "Hold 20-30 seconds, 3 reps each leg", frequency: "1x per day",
    tips: "Keep the standing knee aligned over the foot, not caving inward. Stop if sharp pain.", equipment: "none" },
  { name: "Side-Lying Hip Abduction", region: "knee", type: "strengthening",
    instructions: ["Lie on your side with both legs straight and stacked.", "Keep the top leg straight with the toes pointing forward.", "Lift the top leg upward without rolling your hips back.", "Lower slowly and repeat, then switch sides."],
    dosage: "10-15 reps, 2-3 sets each side", frequency: "1x per day",
    tips: "Strong outer-hip muscles help track the kneecap and ease knee pain. Stop if sharp pain.", equipment: "none" }
];
